{% set version = environ.get('PKG_VERSION', '0.0.0') %}

package:
  name: openghg_defs
  version: "{{ version }}"

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_depth: 1

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python

test:
  imports:
    - openghg_defs

about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "Supplementary definition data for OpenGHG"
