[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "openghg_defs"
version = "0.0.4"
description = "Supplementary definition data for OpenGHG"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
"Homepage" = "https://github.com/openghg/openghg_defs"
"Bug Tracker" = "https://github.com/openghg/openghg_defs/issues"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"openghg_defs" = ["*"]
"openghg_defs.data" = ["*"]
"openghg_defs.data.domain" = ["*"]

