[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openghg_defs"
version = "0.0.4"
description = "Supplementary definition data for OpenGHG"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

[project.urls]
"Homepage" = "https://github.com/openghg/openghg_defs"
"Bug Tracker" = "https://github.com/openghg/openghg_defs/issues"

[tool.setuptools.packages.find]
where = ["."]
